In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## load dataset

In [5]:
df=pd.read_csv(r'placement.csv')
df

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s   CGPA   degree_t  \
0        1      M  67.00   Others  91.00   Others  Commerce  58.00   Sci&Tech   
1        2      M  79.33  Central  78.33   Others   Science  77.48   Sci&Tech   
2        3      M  65.00  Central  68.00  Central      Arts  64.00  Comm&Mgmt   
3        5      M  85.80  Central  73.60  Central  Commerce  73.30  Comm&Mgmt   
4        8      M  82.00  Central  64.00  Central   Science  66.00   Sci&Tech   
..     ...    ...    ...      ...    ...      ...       ...    ...        ...   
210    199      F  67.00  Central  70.00  Central  Commerce  65.00     Others   
211    202      M  54.20  Central  63.00   Others   Science  58.00  Comm&Mgmt   
212    207      M  41.00  Central  42.00  Central   Science  60.00  Comm&Mgmt   
213    209      F  43.00  Central  60.00   Others   Science  65.00  Comm&Mgmt   
214    215      M  62.00  Central  58.00   Others   Science  53.00  Comm&Mgmt   

    workex  etest_p specialisation  Masters      status  
0       No    55.00         Mkt&HR    58.80      Placed  
1      Yes    86.50        Mkt&Fin    66.28      Placed  
2       No    75.00        Mkt&Fin    57.80      Placed  
3       No    96.80        Mkt&Fin    55.50      Placed  
4      Yes    67.00        Mkt&Fin    62.14      Placed  
..     ...      ...            ...      ...         ...  
210     No    88.00         Mkt&HR    71.96  Not Placed  
211     No    79.00         Mkt&HR    58.44  Not Placed  
212     No    97.00        Mkt&Fin    53.39  Not Placed  
213     No    92.66         Mkt&HR    62.92  Not Placed  
214     No    89.00         Mkt&HR    60.22  Not Placed  

[215 rows x 14 columns]

## drop the columns

In [6]:
df.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s   CGPA   degree_t  \
0      1      M  67.00   Others  91.00   Others  Commerce  58.00   Sci&Tech   
1      2      M  79.33  Central  78.33   Others   Science  77.48   Sci&Tech   
2      3      M  65.00  Central  68.00  Central      Arts  64.00  Comm&Mgmt   
3      5      M  85.80  Central  73.60  Central  Commerce  73.30  Comm&Mgmt   
4      8      M  82.00  Central  64.00  Central   Science  66.00   Sci&Tech   

  workex  etest_p specialisation  Masters  status  
0     No     55.0         Mkt&HR    58.80  Placed  
1    Yes     86.5        Mkt&Fin    66.28  Placed  
2     No     75.0        Mkt&Fin    57.80  Placed  
3     No     96.8        Mkt&Fin    55.50  Placed  
4    Yes     67.0        Mkt&Fin    62.14  Placed

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sl_no           215 non-null    int64  
 1   gender          215 non-null    object 
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object 
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object 
 6   hsc_s           215 non-null    object 
 7   CGPA            215 non-null    float64
 8   degree_t        215 non-null    object 
 9   workex          215 non-null    object 
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object 
 12  Masters         215 non-null    float64
 13  status          215 non-null    object 
dtypes: float64(5), int64(1), object(8)
memory usage: 23.6+ KB


In [9]:
df.drop('sl_no',axis=1)

gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s   CGPA   degree_t workex  \
0        M  67.00   Others  91.00   Others  Commerce  58.00   Sci&Tech     No   
1        M  79.33  Central  78.33   Others   Science  77.48   Sci&Tech    Yes   
2        M  65.00  Central  68.00  Central      Arts  64.00  Comm&Mgmt     No   
3        M  85.80  Central  73.60  Central  Commerce  73.30  Comm&Mgmt     No   
4        M  82.00  Central  64.00  Central   Science  66.00   Sci&Tech    Yes   
..     ...    ...      ...    ...      ...       ...    ...        ...    ...   
210      F  67.00  Central  70.00  Central  Commerce  65.00     Others     No   
211      M  54.20  Central  63.00   Others   Science  58.00  Comm&Mgmt     No   
212      M  41.00  Central  42.00  Central   Science  60.00  Comm&Mgmt     No   
213      F  43.00  Central  60.00   Others   Science  65.00  Comm&Mgmt     No   
214      M  62.00  Central  58.00   Others   Science  53.00  Comm&Mgmt     No   

     etest_p specialisation  Masters      status  
0      55.00         Mkt&HR    58.80      Placed  
1      86.50        Mkt&Fin    66.28      Placed  
2      75.00        Mkt&Fin    57.80      Placed  
3      96.80        Mkt&Fin    55.50      Placed  
4      67.00        Mkt&Fin    62.14      Placed  
..       ...            ...      ...         ...  
210    88.00         Mkt&HR    71.96  Not Placed  
211    79.00         Mkt&HR    58.44  Not Placed  
212    97.00        Mkt&Fin    53.39  Not Placed  
213    92.66         Mkt&HR    62.92  Not Placed  
214    89.00         Mkt&HR    60.22  Not Placed  

[215 rows x 13 columns]

## catgorising col for further labelling


In [10]:
df["gender"] = df["gender"].astype('category')
df["ssc_b"] = df["ssc_b"].astype('category')
df["hsc_b"] = df["hsc_b"].astype('category')
df["degree_t"] = df["degree_t"].astype('category')
df["workex"] = df["workex"].astype('category')
df["specialisation"] = df["specialisation"].astype('category')
df["status"] = df["status"].astype('category')
df["hsc_s"] = df["hsc_s"].astype('category')

df.dtypes

sl_no                int64
gender            category
ssc_p              float64
ssc_b             category
hsc_p              float64
hsc_b             category
hsc_s             category
CGPA               float64
degree_t          category
workex            category
etest_p            float64
specialisation    category
Masters            float64
status            category
dtype: object

##  labelling the columns

In [11]:
df["gender"] = df["gender"].cat.codes
df["ssc_b"] = df["ssc_b"].cat.codes
df["hsc_b"] = df["hsc_b"].cat.codes
df["degree_t"] = df["degree_t"].cat.codes
df["workex"] = df["workex"].cat.codes
df["specialisation"] = df["specialisation"].cat.codes
df["status"] = df["status"].cat.codes
df["hsc_s"] = df["hsc_s"].cat.codes
df

sl_no  gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s   CGPA  degree_t  \
0        1       1  67.00      1  91.00      1      1  58.00         2   
1        2       1  79.33      0  78.33      1      2  77.48         2   
2        3       1  65.00      0  68.00      0      0  64.00         0   
3        5       1  85.80      0  73.60      0      1  73.30         0   
4        8       1  82.00      0  64.00      0      2  66.00         2   
..     ...     ...    ...    ...    ...    ...    ...    ...       ...   
210    199       0  67.00      0  70.00      0      1  65.00         1   
211    202       1  54.20      0  63.00      1      2  58.00         0   
212    207       1  41.00      0  42.00      0      2  60.00         0   
213    209       0  43.00      0  60.00      1      2  65.00         0   
214    215       1  62.00      0  58.00      1      2  53.00         0   

     workex  etest_p  specialisation  Masters  status  
0         0    55.00               1    58.80       1  
1         1    86.50               0    66.28       1  
2         0    75.00               0    57.80       1  
3         0    96.80               0    55.50       1  
4         1    67.00               0    62.14       1  
..      ...      ...             ...      ...     ...  
210       0    88.00               1    71.96       0  
211       0    79.00               1    58.44       0  
212       0    97.00               0    53.39       0  
213       0    92.66               1    62.92       0  
214       0    89.00               1    60.22       0  

[215 rows x 14 columns]

## selecting the features and labels



In [13]:
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values
 

## display dependent variables

In [16]:
X

array([[  1.  ,   1.  ,  67.  , ...,  55.  ,   1.  ,  58.8 ],
       [  2.  ,   1.  ,  79.33, ...,  86.5 ,   0.  ,  66.28],
       [  3.  ,   1.  ,  65.  , ...,  75.  ,   0.  ,  57.8 ],
       ...,
       [207.  ,   1.  ,  41.  , ...,  97.  ,   0.  ,  53.39],
       [209.  ,   0.  ,  43.  , ...,  92.66,   1.  ,  62.92],
       [215.  ,   1.  ,  62.  , ...,  89.  ,   1.  ,  60.22]])

In [17]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

## traing and test the data

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.2) 


## Display the data

In [20]:
df.head()

sl_no  gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s   CGPA  degree_t  workex  \
0      1       1  67.00      1  91.00      1      1  58.00         2       0   
1      2       1  79.33      0  78.33      1      2  77.48         2       1   
2      3       1  65.00      0  68.00      0      0  64.00         0       0   
3      5       1  85.80      0  73.60      0      1  73.30         0       0   
4      8       1  82.00      0  64.00      0      2  66.00         2       1   

   etest_p  specialisation  Masters  status  
0     55.0               1    58.80       1  
1     86.5               0    66.28       1  
2     75.0               0    57.80       1  
3     96.8               0    55.50       1  
4     67.0               0    62.14       1

## Model Logistic Regression

In [31]:
from sklearn.linear_model import LogisticRegression
 
Lr=LogisticRegression(random_state=0, solver='lbfgs',max_iter=1000).fit(X_train,Y_train)


In [32]:
Lr.score(X_test,Y_test)

0.8604651162790697

## predicting for random value


In [44]:
Lr.predict([[0, 87, 0, 95, 0, 2, 78, 2, 0, 0, 1, 0]])

ValueError: X has 12 features, but LogisticRegression is expecting 13 features as input.

## creating a Y_pred for test data





In [36]:
Y_pred = Lr.predict(X_test)

## Display predicted values


In [37]:
Y_pred

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1],
      dtype=int8)

In [38]:
# evaluation of the classifier
from sklearn.metrics import confusion_matrix, accuracy_score



[[11  4]
 [ 2 26]]
0.8604651162790697


In [41]:
# display confusion matrix
print("confusion matrix:",confusion_matrix(Y_test, Y_pred))


confusion matrix: [[11  4]
 [ 2 26]]


In [42]:
# display accuracy
print("accuracy score:",accuracy_score(Y_test, Y_pred))

accuracy score: 0.8604651162790697
